#### configuration

VERSION        = 3.16.0
NAME           = vimperator
UUID           = vimperator@mozdev.org
MIN_VERSION    = 38.0
MAX_VERSION    = 51.0

-include private.properties

include ../common/Makefile
