#### configuration

VERSION        = 3.15.0
NAME           = vimperator
UUID           = vimperator@mozdev.org
MIN_VERSION    = 38.0
MAX_VERSION    = 50.0

-include private.properties

include ../common/Makefile
